
/* simple types */

//pick ( ST_NULL,    MT_EMPTY,  USE_EMPTY ) /* v2.05: obsolete */
pick ( ST_BYTE,    MT_BYTE,   USE_EMPTY )
pick ( ST_SBYTE,   MT_SBYTE,  USE_EMPTY )
pick ( ST_WORD,    MT_WORD,   USE_EMPTY )
pick ( ST_SWORD,   MT_SWORD,  USE_EMPTY )
pick ( ST_DWORD,   MT_DWORD,  USE_EMPTY )
pick ( ST_SDWORD,  MT_SDWORD, USE_EMPTY )
pick ( ST_REAL4,   MT_REAL4,  USE_EMPTY )
pick ( ST_FWORD,   MT_FWORD,  USE_EMPTY )
pick ( ST_QWORD,   MT_QWORD,  USE_EMPTY )
pick ( ST_SQWORD,  MT_SQWORD, USE_EMPTY )
pick ( ST_REAL8,   MT_REAL8,  USE_EMPTY )
pick ( ST_TBYTE,   MT_TBYTE,  USE_EMPTY )
pick ( ST_REAL10,  MT_REAL10, USE_EMPTY )
pick ( ST_OWORD,   MT_OWORD,  USE_EMPTY )
pick ( ST_NEAR,    MT_NEAR,   USE_EMPTY )
pick ( ST_NEAR16,  MT_NEAR,   USE16     )
pick ( ST_NEAR32,  MT_NEAR,   USE32     )
pick ( ST_FAR,     MT_FAR,    USE_EMPTY )
pick ( ST_FAR16,   MT_FAR,    USE16     )
pick ( ST_FAR32,   MT_FAR,    USE32     )
pick ( ST_PROC,    MT_NEAR,   USE_EMPTY )
pick ( ST_PTR,     MT_PTR,    USE_EMPTY )
