
// simple types

pick ( NULL,    MT_EMPTY,  USE_EMPTY ) /* still needed! See types.c */
pick ( BYTE,    MT_BYTE,   USE_EMPTY )
pick ( SBYTE,   MT_SBYTE,  USE_EMPTY )
pick ( WORD,    MT_WORD,   USE_EMPTY )
pick ( SWORD,   MT_SWORD,  USE_EMPTY )
pick ( DWORD,   MT_DWORD,  USE_EMPTY )
pick ( SDWORD,  MT_SDWORD, USE_EMPTY )
pick ( REAL4,   MT_REAL4,  USE_EMPTY )
pick ( FWORD,   MT_FWORD,  USE_EMPTY )
pick ( QWORD,   MT_QWORD,  USE_EMPTY )
pick ( SQWORD,  MT_SQWORD, USE_EMPTY )
pick ( REAL8,   MT_REAL8,  USE_EMPTY )
pick ( TBYTE,   MT_TBYTE,  USE_EMPTY )
pick ( REAL10,  MT_REAL10, USE_EMPTY )
pick ( OWORD,   MT_OWORD,  USE_EMPTY )
pick ( NEAR,    MT_NEAR,   USE_EMPTY )
pick ( NEAR16,  MT_NEAR,   USE16     )
pick ( NEAR32,  MT_NEAR,   USE32     )
pick ( FAR,     MT_FAR,    USE_EMPTY )
pick ( FAR16,   MT_FAR,    USE16     )
pick ( FAR32,   MT_FAR,    USE32     )
pick ( PROC,    MT_NEAR,   USE_EMPTY )
pick ( PTR,     MT_PTR,    USE_EMPTY )
