
// simple types

pick ( NULL,    MT_EMPTY,       0  , VOID_TYPE,  OFSSIZE_EMPTY )
pick ( BYTE,    MT_BYTE,        1  , UINT_TYPE,  OFSSIZE_EMPTY )
pick ( SBYTE,   MT_SBYTE,       1  , INT_TYPE,   OFSSIZE_EMPTY )
pick ( WORD,    MT_WORD,        2  , UINT_TYPE,  OFSSIZE_EMPTY )
pick ( SWORD,   MT_SWORD,       2  , INT_TYPE,   OFSSIZE_EMPTY )
pick ( DWORD,   MT_DWORD,       4  , UINT_TYPE,  OFSSIZE_EMPTY )
pick ( SDWORD,  MT_SDWORD,      4  , INT_TYPE,   OFSSIZE_EMPTY )
pick ( REAL4,   MT_DWORD,       4  , FLOAT_TYPE, OFSSIZE_EMPTY )
pick ( FWORD,   MT_FWORD,       6  , UINT_TYPE,  OFSSIZE_EMPTY )
pick ( QWORD,   MT_QWORD,       8  , UINT_TYPE,  OFSSIZE_EMPTY )
pick ( REAL8,   MT_QWORD,       8  , FLOAT_TYPE, OFSSIZE_EMPTY )
pick ( TBYTE,   MT_TBYTE,      10  , UINT_TYPE,  OFSSIZE_EMPTY )
pick ( REAL10,  MT_TBYTE,      10  , FLOAT_TYPE, OFSSIZE_EMPTY )
pick ( OWORD,   MT_OWORD,      16  , UINT_TYPE,  OFSSIZE_EMPTY )
pick ( NEAR,    MT_NEAR,       -1  , ADDR_TYPE,  OFSSIZE_EMPTY )
pick ( NEAR16,  MT_NEAR,        2  , ADDR_TYPE,  OFSSIZE_16    )
pick ( NEAR32,  MT_NEAR,        4  , ADDR_TYPE,  OFSSIZE_32    )
pick ( FAR,     MT_FAR,        -1  , ADDR_TYPE,  OFSSIZE_EMPTY )
pick ( FAR16,   MT_FAR,         4  , ADDR_TYPE,  OFSSIZE_16    )
pick ( FAR32,   MT_FAR,         6  , ADDR_TYPE,  OFSSIZE_32    )
pick ( PROC,    MT_NEAR,       -1  , ADDR_TYPE,  OFSSIZE_EMPTY )
