"   JWasm [options] asm-file [options] [asm-file] ... [@env_var]\n"
"\n"
"options:\n"
"-<0|1|2|3|4|5|6>[p] Instructions accepted for 8086(=0), 80186(=1),\n"
"                    80286(=2), 80386(=3), 80486(=4), Pentium(=5) or\n"
"                    Pentium Pro(=6) cpu. <p> allows privileged\n"
"                    instructions.\n"
#if BIN_SUPPORT
"-bin                Generate plain binary file\n"
#endif
"-c                  Assemble without linking (always set)\n"
#if COFF_SUPPORT
"-coff               Generate COFF format object file\n"
#endif
"-C<p|u|x>           set OPTION CASEMAP: p=NONE, u=ALL,\n"
"                    x=NOTPUBLIC (default).\n"
"-D<name>[=text]     Define text macro\n"
#ifdef DEBUG_OUT
"-d6                 Display debug trace on stdout\n"
#endif
"-e<number>          Set error limit number (default=50)\n"
#if ELF_SUPPORT
"-elf                Generate ELF format object file\n"
#endif
"-EP                 Output preprocessed listing to stdout\n"
"-Fi<file_name>      Force <file_name> to be included\n"
"-Fl[=<file_name>]   Write listing file\n"
"-Fo<file_name>      Set object file name\n"
"-Fr<file_name>      Set error file name\n"
"-FPi                80x87 instructions with emulation fixups\n"
"-FPi87              80x87 instructions (default)\n"
"-fpc                Disallow floating-point instructions (.NO87)\n"
"-fp<n>              Floating-point instructions for 8087(n=0), 80287(n=2),\n"
"                    80387(n=3), Pentium(n=5) or Pentium Pro(n=6).\n"
"-G<c|d|z>           Use Pascal, C or Stdcall calling convention\n"
"-I<directory>       Add directory to list of include directories\n"
"-j                  Force signed types to be used for signed values\n"
"-m<t|s|m|c|l|h|f>   Set memory model:\n"
"                    (Tiny, Small, Medium, Compact, Large, Huge, Flat)\n"
"-n<d|m|t>=<name>    Set name of data segment, module or text segment\n"
#if COCTALS
"-o                  Allow C form of octal constants\n"
#endif
"-omf                Generate OMF format object file (default)\n"
#ifdef DEBUG_OUT
"-pm=<n>             Stop assembly after <n> passes\n"
#endif
"-q, -nologo         Don't display version and copyright information\n"
"-Sa                 Maximize source listing\n"
"-Sg                 Display generated code in listing\n"
"-Sn                 Suppress symbol-table listing\n"
"-Sx                 List false conditionals\n"
"-w                  Same as /W0 /WX\n"
"-W<number>          Set warning level number (default=2, max=4)\n"
"-WX                 Treat all warnings as errors\n"
"-zcm                Set C name mangler to standard mode (default)\n"
"-zcw                Set C name mangler to Watcom compatible mode\n"
"-Zd                 Add line number debug information\n"
"-Zf                 Make all symbols public\n"
"-Zi                 Symbolic debug info (not implemented yet)\n"
"-zlc                No OMF records about data in code\n"
"-zld                No OMF records about file dependencies\n"
"-zlf                No COFF .file entry in symbol table\n"
"-zls                No COFF auxiliary entries for sections in symbol table\n"
"-Zm                 Masm v5.1 compatibility\n"
"-Zne                Disable syntax extensions not supported by Masm\n"
"-Zp[n]              Set structure alignment, n=<1|2|4|8|16|32>\n"
"-zzo                No name decoration for STDCALL symbols\n"
"-zzp                No '@size' suffix for STDCALL procedure names\n"
"-zzs                Store decorated name of start address (COFF only)\n"
"@env_var            Environment variable or file containing further commands\n"
