"   JWasm [options] asm-file [options] [asm-file] ... [@env_var]\n"
"\n"
"options:\n"
"-{0,1,2,3,4,5,6}{p} instructions accepted for 8086(=0), 80186(=1),\n"
"                    80286(=2), 80386(=3), 80486(=4), Pentium(=5) or\n"
"                    Pentium Pro(=6) cpu. {p} suffix includes privileged\n"
"                    instructions.\n"
#if BIN_SUPPORT
"-bin                generate plain binary file\n"
#endif
"-c                  assemble without linking (always set)\n"
#if COFF_SUPPORT
"-coff               generate COFF format object file\n"
#endif
"-Cp                 preserve case of identifiers\n"
"-D<name>[=text]     define text macro\n"
"-e<number>          set error limit number (default=50)\n"
#if ELF_SUPPORT
"-elf                generate ELF format object file\n"
#endif
"-EP                 Output preprocessed listing to stdout\n"
"-Fi<file_name>      force <file_name> to be included\n"
"-Fl[=<file_name>]   write listing file\n"
"-Fo<file_name>      set object file name\n"
"-Fr<file_name>      set error file name\n"
"-FPi                80x87 instructions with emulation fixups\n"
"-FPi87              80x87 instructions (default)\n"
"-fpc                disallow floating-point instructions (.NO87)\n"
"-fp{n}              floating-point instructions for 8087(n=0), 80287(n=2),\n"
"                    80387(n=3), Pentium(n=5) or Pentium Pro(n=6).\n"
"-G{c,d,z}           Use Pascal, C or Stdcall calling convention\n"
"-I<directory>       add directory to list of include directories\n"
"-j                  force signed types to be used for signed values\n"
"-m{t,s,m,c,l,h,f}   set memory model:\n"
"                    (Tiny, Small, Medium, Compact, Large, Huge, Flat)\n"
"-n{d,m,t}=<name>    set name of {data segment, module, text segment}\n"
"-o                  allow C form of octal constants\n"
"-omf                generate OMF format object file (default)\n"
"-q, -nologo         don't display version and copyright information\n"
"-Sg                 display generated code in listing (always set)\n"
"-Sn                 suppress symbol-table listing\n"
"-w                  same as /W0 /WX\n"
"-W<number>          set warning level number (default=2, max=4)\n"
"-WX                 treat all warnings as errors\n"
"-zcm                set C name mangler to standard mode (default)\n"
"-zcw                set C name mangler to Watcom compatible mode\n"
"-Zd                 add line number debug information\n"
"-Zi                 symbolic debug info (not implemented yet)\n"
"-zlc                no OMF records about data in code\n"
"-zld                no OMF records about file dependencies\n"
"-zlf                no COFF .file entry in symbol table\n"
"-zls                no COFF auxiliary entries for sections in symbol table\n"
"-Zm                 Masm v5.1 compatibility\n"
"-Zp[n]              set structure alignment, n={1,2,4,8,16,32}\n"
"-zzo                no name decoration for STDCALL symbols\n"
"-zzp                no '@size' suffix for STDCALL procedure names\n"
"-zzs                store decorated name of start address (COFF only)\n"
"@env_var            environment variable or file containing further commands\n"
